export const API_URL = "https://api.themoviedb.org/3"
export const API_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI2ZWNhYjNmODYwMGY2M2E3ZjNmMTE0YzQyZTk5NzRiZCIsInN1YiI6IjYzMjJjNzg5MzNhZDhmMDA4YTY3MzcwMSIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.jFvI-JDKyWe2hcPMNfsPas45XU6VvL0pF-6ZoR2Y0I8"
